# Generated by Django 4.1.7 on 2023-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_userstat_followers_alter_userstat_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='replies', to='network.post'),
        ),
    ]
