# Generated by Django 4.1.7 on 2023-04-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_parent_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='child_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='replies', to='network.post'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_parent_post', to='network.post'),
        ),
    ]
